# Generated by Django 3.1.7 on 2021-02-23 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210223_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'confirm'), (2, 'reject'), (3, 'pending')]),
        ),
    ]
